heat_template_version: 2015-04-30

resources:
  gremlin_keypair:
    type: OS::Nova::KeyPair
    properties:
      name: gremlin_key
      save_private_key: true

  gremlin_security_groups:
    type: OS::Neutron::SecurityGroup
    properties:
      name: gremlin_sg
      rules:
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22
          direction: ingress

  gremlin_instance:
    type: OS::Nova::Server
    properties:
      name: gremlin_ovs_flows
      flavor: {{ stack_vm_flavor }}
      image: {{ stack_vm_image }}
      key_name: {get_resource: gremlin_keypair}
      networks:
        - network: {{ stack_vm_net }}
      security_groups:
        - {get_resource: gremlin_security_groups}

outputs:
  gremlin_private_key:
    description: The private key for instances created by gremlin
    value: {get_attr: [gremlin_keypair, private_key]}
